language: python
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - python test.py
  - coverage run test.py
  - coverage report
  - codecov -token=$CODECOV_TOKEN

deploy:
  provider: pypi
  login: $PYPI_LOGIN
  password: $PYPI_PASSWORD
  on:
    branch: release